Operations to get elements or properties of an array

In [1]:
import numpy as np

In [2]:
an_array = np.arange(0,11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
first_element = an_array[0]
print(first_element)
last_element = an_array[len(an_array) - 1]
print(last_element)

0
10


In [4]:
first_five = an_array[0:5]
print(first_five)
skip_two = an_array[0::2]
print(skip_two)
count_down = an_array[5::-1] #a stride
print(count_down)
last_item = an_array[:-1]
print(last_element)
last_two = an_array[-2:]
print(last_two)
count_until_last_two = an_array[:-2]
print(count_until_last_two)

[0 1 2 3 4]
[ 0  2  4  6  8 10]
[5 4 3 2 1 0]
10
[ 9 10]
[0 1 2 3 4 5 6 7 8]


In [5]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(an_array.size) # prints the array size
print(len(an_array))
print(np.amax(an_array)) #returns the max of an arrayed 
normal_array = list(range(0,10))
print(normal_array)
print(len(normal_array))
print(np.amin(an_array))
print(np.average(an_array))

11
11
10
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10
0
5.0
