In [1]:
#KNN separates data into regions i.e. 'classification'
#k - value checks the closest 'k' neighbors around the datapoint
#weights - uniform gives equal importance to data points
#weights - distance gives more importance to closer data points

In [2]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv('files/car.data')

In [4]:
print(data.keys())

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')


In [5]:
print(data.head()) # I added the headings into the dataset

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [6]:
X = data[[ # retrieve the data that we want to analyze
    'buying',
    'maint',
    'safety'
]].values
y = data[['class']] # retrieve the targets/class
print(X, y) 

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [7]:
#converting the data
#Converting X
Le = LabelEncoder() #Encode target labels with value between 0 and n_classes-1. (assign a numeric value to each class)
for i in range(len(X[0])):
    X[:,i] = Le.fit_transform(X[:,i]) #
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [8]:
#converting y
label_mapping = {
    'unacc': 0,
    'acc': 1,
    'good': 2,
    'vgood': 3
}
y['class'] = y['class'].map(label_mapping) #will map the labels inside of the arrays
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-8-550429200290>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping) #will map the labels inside of the arrays


In [14]:
#creating a model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')
#we want to compare the output of the model (which is the trained training data)\
#to the testing data and that gives us the accuracy
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test) # gather prediction values for testing purposes000000000000000
accuracy = metrics.accuracy_score(y_test, predictions)
print("prediction", predictions)
print("accuracy", accuracy)

prediction [0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0
 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0
 0 1 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1
 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 1 0]
accuracy 0.7456647398843931


<ipython-input-14-9937b2ebb6d4>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(X_train, y_train)


In [17]:
print("actual value", y[20])
print("predicted value", knn.predict(X)[20])
print("actual value", y[2])
print("predicted value", knn.predict(X)[2])

actual value [0]
predicted value 0
actual value [0]
predicted value 0
