In [1]:
import numpy as np

In [3]:
a_matrix = np.matrix('1 2; 3 4')
print(a_matrix)

[[1 2]
 [3 4]]


In [11]:
a_matrix[1,0] = 10
print(a_matrix)
a_matrix[0] = [6, 3]
print(a_matrix)

[[ 6  3]
 [10  4]]
[[ 6  3]
 [10  4]]


In [17]:
print(np.sort(a_matrix)) # you can sort a matrix
print(-np.sort(-a_matrix)) # you can reverse sort a matrix

[[ 3  6]
 [ 4 10]]
[[ 6  3]
 [10  4]]
