In [1]:
import numpy as np

In [9]:
a_matrix = np.matrix('1 2 3; 4 5 6; 7 8 9')
true_false_matrix = np.matrix('True True; False False')
print(a_matrix)
print(true_false_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True]
 [False False]]


In [16]:
print(a_matrix[0])
print(type(a_matrix[0]))
print(a_matrix[1,0])
print(a_matrix[2, 1:3]) #goes to index 2 row then range 1:3 index
print(a_matrix.size) # total number of items in matrix
print(a_matrix.shape) # returns a tuple that is the shape of the matrix

[[1 2 3]]
<class 'numpy.matrix'>
4
[[8 9]]
9
(3, 3)


In [19]:
print(np.amax(a_matrix))
print(np.amin(a_matrix))
print(np.average(a_matrix))

9
1
5.0


In [22]:
print(a_matrix.max())
print(a_matrix.min())
print(a_matrix.mean())

9
1
5.0
