In [1]:
import numpy as np

In [4]:
an_array = np.arange(0,6)
print(an_array)

[0 1 2 3 4 5]


In [6]:
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5]


In [21]:
an_array = np.arange(0,6)
print(an_array)
print(np.append(an_array, [6, 7, 8, 9]))
append_copy = np.append(an_array, [6,7,8,9,10])
print(append_copy)
insert_copy = np.insert(an_array, 0, [10, 11]) # inserts 10, 11 at 0 index
print(insert_copy)
delete_copy = np.delete(an_array, 3) # deletes the 3rd index
print(delete_copy)
print(an_array)

[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[10 11  0  1  2  3  4  5]
[0 1 2 4 5]
[0 1 2 3 4 5]


In [23]:
print(an_array * 2) #takes every element and multiplies it by two similiar to map
print(an_array + 2) #takes all elements and adds 2

[ 0  2  4  6  8 10]
[2 3 4 5 6 7]


In [28]:
another_array = np.array([3, 6, 21, 9, 10, 1])
another_array = np.sort(another_array) # sort in asc order
another_array = -np.sort(-another_array) # sort in desc order
print(another_array)

[21 10  9  6  3  1]
