In [1]:
import numpy as np

In [4]:
#matrixes are used in images, geological data, machine learning, and anything graph related
one_matrix = np.array([[0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0]])
print(one_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [8]:
two_by_two = np.matrix([[1,2],
           [3,4]])
print(two_by_two)

[[1 2]
 [3 4]]


In [10]:
two_by_three = np.matrix('1 2; 3 4; 5 6')
print(two_by_three)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
print(np.zeros([3,2])) # you can use np zeroes to create a matrix
print(np.ones([3,3]))


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
