Student Grades App

In [2]:
import numpy as np
student_grades = np.array([56, 78, 98, 90, 58, 64, 67, 72, 93, 51])
print(student_grades)

[56 78 98 90 58 64 67 72 93 51]


In [4]:
class_average = np.average(student_grades) # getting the class average
print(class_average)

72.7


In [7]:
highest_grade = np.amax(student_grades)
print(highest_grade)

lowest_grade = np.amin(student_grades)
print(lowest_grade)

98
51


In [11]:
max_index = np.argmax(student_grades)
min_index = np.argmin(student_grades)
print(f'Index of max is {max_index}')
print(f'Index of min is {min_index}')

Index of max is 2
Index of min is 9


In [14]:
asc_order = np.sort(student_grades)
desc_order = -np.sort(-student_grades)
print(asc_order)
print(desc_order)

[51 56 58 64 67 72 78 90 93 98]
[98 93 90 78 72 67 64 58 56 51]


In [17]:
increase_grades = student_grades + 10
print(increase_grades)

[ 66  88 108 100  68  74  77  82 103  61]


In [18]:
increased_ones = np.add(student_grades, np.ones(10))
print(increased_ones)


[57. 79. 99. 91. 59. 65. 68. 73. 94. 52.]
