In [15]:
#SVMs are effective high dimensional spaces
#many kernel functions
#SVM can be used for classification and regression
"""
Pros

Accuracy
Works well on smaller cleaner datasets
It can be more efficient because it uses a subset of training points
Cons

Isn’t suited to larger datasets as the training time with SVMs can be high
Less effective on noisier datasets with overlapping classes

SVM is used for text classification tasks such as category assignment, detecting spam and sentiment 
analysis. It is also commonly used for image recognition challenges, performing particularly well in 
aspect-based recognition and color-based classification. SVM also plays a vital role in many areas of
handwritten digit recognition, such as postal automation services.
"""

'\nPros\n\nAccuracy\nWorks well on smaller cleaner datasets\nIt can be more efficient because it uses a subset of training points\nCons\n\nIsn’t suited to larger datasets as the training time with SVMs can be high\nLess effective on noisier datasets with overlapping classes\n\nSVM is used for text classification tasks such as category assignment, detecting spam and sentiment \nanalysis. It is also commonly used for image recognition challenges, performing particularly well in \naspect-based recognition and color-based classification. SVM also plays a vital role in many areas of\nhandwritten digit recognition, such as postal automation services.\n'

In [16]:
from sklearn import datasets, svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [17]:
iris = datasets.load_iris()

In [18]:
X = iris.data # get instances
y = iris.target # get features
print(X)
print(y)
print(X.shape)
print(y.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [30]:
classes = ['Iris Setosa', 'Iris Versicolour', 'Iris Virginica']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)
model = svm.SVC()
model.fit(X_train, y_train)
print("y_tests:    ", y_test)
predictions = model.predict(X_test)
print("predictions:", predictions)
acc = accuracy_score(y_test, predictions)
print(acc)

X_test shape: (30, 4)
y_test shape: (30,)
y_tests:     [1 2 2 2 2 0 2 2 2 1 0 0 2 1 0 0 1 0 1 1 1 2 2 2 0 2 0 2 1 0]
predictions: [1 2 2 2 2 0 2 1 2 1 0 0 2 1 0 0 1 0 1 1 1 1 1 2 0 2 0 2 1 0]
0.9
